### ISSUE TITLE
Transient Expiry Not User Configurable for Local Base

### ISSUE THREAD

**Issue by CompKingCanada** [Ecwid/ecwid-wordpress-plugin#241]
I was chasing a problem for years where I had to disconnect and reconnect my store in order for Product Updates to appear on my website for crawling purposes.  It kept penalizing me on Google Search Console.

The problem is related to Transients stored locally in the WP Database with a long expiry [1 month].  This timeframe needs to be shortened or user configrable.

My problem was I had enabled "ecwid_local_base_enabled" option to allow local search/caching.

The specific code where this problem occurs is: ecwid-shopping-cart/lib/ecwid_platform.php Line: 406

**Comment by meteor-ec** [comment]
Hi,

This is Ilnur from Ecwid.

Thank you for your report! I'll look into this issue and I'll come back with an answer soon.

**Comment by meteor-ec** [comment]
Hi,

This is Ilnur from Ecwid.

Thank you for your message.

Could you say why you decide to use "ecwid_local_base_enabled"? You can choose not to use this feature because products can be indexed from store pages and sitemaps well (https://support.ecwid.com/hc/en-us/articles/360003869899-Submitting-a-sitemap-to-Google#third-party-services). Or do you have another reason for using it?

**Comment by CompKingCanada** [comment]
I use it for various reasons, incuding SiteMap tagging of update date/time, search integration with WP Search, and speed.

**Comment by meteor-ec** [comment]
Hi!

We've released improvements for "transients" in the 6.10.22 version, please try to update your plugin.
