### ISSUE TITLE
white label sidebar naming

### ISSUE THREAD

**Issue by jimlongo56** [Ecwid/ecwid-wordpress-plugin#7]
Hope I got the right repo.

When using the plugin in **whitelabel** situations we run into the following.

Plugin uses the `brand` from the config file in various places. One of them is in the sidebar.
![screen shot 2017-11-15 at 2 48 38 pm](https://user-images.githubusercontent.com/6787988/32857055-a783f2ce-ca14-11e7-8e0e-4b04108fa247.png)

However it seems a little confusing to website owner what this menu item represents.  In your direct channel it's called Ecwid which makes sense.

How about if Shopping Cart was added to it like so?  Makes more sense to user I think.  Could even be another param in config file  `display_name` or something.
![screen shot 2017-11-15 at 2 49 09 pm](https://user-images.githubusercontent.com/6787988/32857060-a9ab4c96-ca14-11e7-99fa-f3f542cda413.png)

**Comment by makfruit** [comment]
Hi Jim,

In some cases, the brand is more general and doesn't mention exact label. Example: "Online Store". Which is why we had to remove "store" and "shopping cart" from the navigation menus and labels. 

Would it be possible for you to use "Big Hosting Store" as a brand?

**Comment by jimlongo56** [comment]
I should ask, but it seems okay to me.

Are you saying that you would append `Store` to the Brand Name we give you?

**Comment by makfruit** [comment]
What I am saying is that we try to avoid adding "store" and "shopping cart" postfixes to the brand name because a lot of brands (including the white label "Online Store" one) already include something like 'store', 'shop' etc. So if we added 'store' there, it would look good in your case "Big Hosting Store", but it would break in other cases, e.g. 'My Hosting Store Store' or 'Reseller Company Shop Store'. 

That's why I suggest adding "store" to the brand in the config if you need that. 

> But to be clear, I can't change the Brand Name, that's not my business. 
Makes sense. But the plugin never explicitly says "Brand name is this", it just uses it in different places, with or without some extra words near it. Put it another way, with the option you suggest you *are* changing 'brand' to "Big Hosting Store" in the navigation and in couple more places. Be it the plugin or you who add 'store', the end user will see the whole phrase, which is the same.

**Comment by jimlongo56** [comment]
So how about another parameter in the config file "plugin_name"?

**Comment by makfruit** [comment]
I am not sure it will be clear where to use one or another. Anyway, we will think about it, thanks.
